name: Greeting from CJW
on: push

jobs:
  greeting-job:
    name: Greeting Job
    runs-on: self-hosted
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: C
        MIDDLE_NAME: J
        LAST_NAME: W
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.       
        echo $PATH
        echo `uname -a`

    - name: Check test nodes ping
      run: |              
        ping -c 3 www.baidu.com
        ping -c 3 acorn.cpt.corigine.com
        ping -c 3 apple.cpt.corigine.com
  
  running-job:
    name: running-test
    needs: greeting-job
    runs-on: self-hosted
    steps:
    - name: Checkout ci-dev-sdn-private
        uses: actions/checkout@v2
        with:
          repository: Corigine/ci-dev-sdn-private
          ref: wip-CICD-175-cjw-test
          path: ci-dev-sdn-private
          token: ${{secrets.ACCESS_TOKEN}}
    - name: Checkout nti-private
        uses: actions/checkout@v2
        with:
          repository: Corigine/nti-private
          ref: nti_with_pycallgraph
          path: nti-private
          token: ${{secrets.ACCESS_TOKEN}}

    - name: Execute bash test
      working-directory: ci-dev-sdn-private/tests/
      shell: bash
      run: |
        bash run_tests.sh
