name: Greeting from CJW
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-18.04
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: C
        MIDDLE_NAME: J
        LAST_NAME: W
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.       
        echo $PATH
        echo `uname -a`

    - name: Check test nodes ping
      run: |              
        echo `ping -c 3 www.baidu.com`
        echo `ping -c 3 acorn.cpt.corigine.com`
        echo `ping -c 3 apple.cpt.corigine.com`
