name: Greeting from CJW
on:
  schedule:
    - cron: '40 10 * * *'

jobs:
  greeting-job:
    name: Greeting Job
    runs-on: self-hosted
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: C
        MIDDLE_NAME: J
        LAST_NAME: W
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.       
        echo $PATH
        echo `uname -a`

    - name: Check test nodes ping
      run: |              
        ping -c 3 www.baidu.com
        ping -c 3 acorn.cpt.corigine.com
        ping -c 3 apple.cpt.corigine.com
  
