name: Greeting from CJW
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-18.04
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: C
        MIDDLE_NAME: J
        LAST_NAME: W
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
